'''
Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are 
generated by the following formulae:

Triangle
 
T_n=n(n+1)/2
 
1, 3, 6, 10, 15, ...


Pentagonal
 
P_n=n(3n - 1)/2
 
1, 5, 12, 22, 35, ...


Hexagonal
 
H_n=n(2n - 1)
 
1, 6, 15, 28, 45, ...


It can be verified that T_{285} = P_{165} = H_{143} = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

'''

from extras.utils import is_pentagonal, is_hexagonal

def tri_pen_hex():

    n = 286
    answer = False

    while not answer:

        t = int(n * (n + 1) / 2)

        if is_pentagonal(t) and is_hexagonal(t):
            answer = t
        
        n += 1
    
    return answer

print("Answer to problem 45: ", tri_pen_hex())


